config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    get 'list', :on => :collection
    get 'edit_page', :on => :collection
  end
  root to: 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/projects_controller.rb
require 'devise'

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/list or /projects/list.json
  def list
    @projects = Project.all
  end
  
  # GET /projects/edit_page or /projects/edit_page.json
  def edit_page
    authenticate_user!
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    authenticate_user!
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authenticate_user!
  end

  # POST /projects or /projects.json
  def create
    authenticate_user!
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    authenticate_user!
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    authenticate_user!
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Porfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/projects/">Software Portfolio</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExampleDefault" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/projects/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/projects/list/">Projects <span class="sr-only">(current)</span></a>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item">
              <a><%= link_to "Sign out", destroy_user_session_path, :method => :delete , :class => "nav-link"%></a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">Sign In / Sign Up <span class="sr-only">(current)</span></a>
            </li>
          <% end %>


        </ul>
      </div>
    </nav>
  
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
  
  <p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
  <% end %>
  </p>

</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit_page.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>

  </head>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Edit Project Page!</h1>
          <p>This website is designed to showcase and provide ease of access for coding projects. Anyone is allowed to view the projects. However, if you want to edit the projects, you will need to authenticate yourself and justify your need to do so.</p>
        </div>
      </div>

      <!---- Cards ----->
      <div class="container-fluid padding">
      <div class="row"> 
          <% @projects.each do |project| %>
            <div class="col-md-4">
              <h2><%=project.title%></h2>
              <p><%=project.description%></p>
              <%= link_to 'Show', project, :class => "btn btn-secondary" %>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
            </div>
            <% end %>
        </div>
        <hr>
      </div> <!-- /container -->
      </main>
</table>

<br>
<%= link_to 'Add New Project', "/projects/new", :class => "btn btn-primary btn-lg btn-block" %>
<br>
<br>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<table>

  </head>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Welcome!</h1>
          <p>This website is designed to showcase and provide ease of access for coding projects. Anyone is allowed to view the projects. However, if you want to edit the projects, you will need to authenticate yourself and justify your need to do so.</p>
        </div>
      </div>

      <!---- Cards ----->
      <div class="container-fluid padding">
      <div class="row"> 
          <% @projects.each do |project| %>
            <div class="col-md-4">
              <h2><%=project.title%></h2>
              <p><%=project.description%></p>
              <%= link_to 'Show', project, :class => "btn btn-secondary" %>
            </div>
            <% end %>
        </div>
        <hr>
      </div> <!-- /container -->
      </main>
</table>

<br>

app/views/projects/list.html.erb
<p id="notice"><%= notice %></p>

<table>

  </head>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Project List!</h1>
          <p>This website is designed to showcase and provide ease of access for coding projects. Anyone is allowed to view the projects. However, if you want to edit the projects, you will need to authenticate yourself and justify your need to do so.</p>
        </div>
      </div>

      <!---- Cards ----->
      <div class="container-fluid padding">
      <div class="row"> 
          <% @projects.each do |project| %>
            <div class="col-md-4">
              <h2><%=project.title%></h2>
              <p><%=project.description%></p>
              <%= link_to 'Show', project, :class => "btn btn-secondary" %>
            </div>
            <% end %>
        </div>
        <hr>
      </div> <!-- /container -->
      </main>
</table>

<br>
<%= link_to 'Edit Projects', "/projects/edit_page", :class => "btn btn-secondary btn-lg btn-block" %>
<br>
<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<table>

  </head>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"><%= @project.title %></h1>
        </div>
      </div>

    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>

    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %>
  </main>
</table>

<br>